name: Test Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

      - name: Success
        run: echo "All tests passed!"
